# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/nexys_hdmi.xdc

# XDC: new/fix_backbone_impl.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0_0 || ORIG_REF_NAME==system_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_0/system_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_microblaze_0_0 || ORIG_REF_NAME==system_microblaze_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_timer_0_0 || ORIG_REF_NAME==system_axi_timer_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_intc_0_0/system_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_intc_0_0 || ORIG_REF_NAME==system_axi_intc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] -quiet

# IP: bd/system/ip/system_v_tc_0_0/system_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_1_0 || ORIG_REF_NAME==system_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/system/ip/system_rgb2dvi_0_0/system_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rgb2dvi_0_0 || ORIG_REF_NAME==system_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/system/ip/system_mig_7series_0_1/system_mig_7series_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_mig_7series_0_1 || ORIG_REF_NAME==system_mig_7series_0_1} -quiet] -quiet

# IP: bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dlmb_v10_0 || ORIG_REF_NAME==system_dlmb_v10_0} -quiet] -quiet

# IP: bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ilmb_v10_0 || ORIG_REF_NAME==system_ilmb_v10_0} -quiet] -quiet

# IP: bd/system/ip/system_dlmb_bram_if_cntlr_0/system_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==system_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/system/ip/system_ilmb_bram_if_cntlr_0/system_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==system_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/system/ip/system_lmb_bram_0/system_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_lmb_bram_0 || ORIG_REF_NAME==system_lmb_bram_0} -quiet] -quiet

# IP: bd/system/ip/system_mdm_1_0/system_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_mdm_1_0 || ORIG_REF_NAME==system_mdm_1_0} -quiet] -quiet

# IP: bd/system/ip/system_reset_inv_0_0/system_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_reset_inv_0_0 || ORIG_REF_NAME==system_reset_inv_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_mig_7series_0_100M_0/system_rst_mig_7series_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==system_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ser_0/system_rst_ser_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ser_0 || ORIG_REF_NAME==system_rst_ser_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_intr0_0/system_xlconstant_intr0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconstant_intr0_0 || ORIG_REF_NAME==system_xlconstant_intr0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_btn_0/system_axi_gpio_btn_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_btn_0 || ORIG_REF_NAME==system_axi_gpio_btn_0} -quiet] -quiet

# IP: bd/system/ip/system_util_or_irq_0/system_util_or_irq_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_or_irq_0 || ORIG_REF_NAME==system_util_or_irq_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_upgraded_ipi_imp_xbar_0/system_axi_interconnect_0_upgraded_ipi_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_upgraded_ipi_imp_xbar_0 || ORIG_REF_NAME==system_axi_interconnect_0_upgraded_ipi_imp_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_pc_6/system_axi_interconnect_0_imp_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_pc_6 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_pc_6} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_us_0/system_axi_interconnect_0_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_us_0 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_us_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_us_1/system_axi_interconnect_0_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_us_1 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_us_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_us_2/system_axi_interconnect_0_imp_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_us_2 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_us_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_pc_7/system_axi_interconnect_0_imp_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_pc_7 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_pc_7} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_us_3/system_axi_interconnect_0_imp_auto_us_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_us_3 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_us_3} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_cc_1/system_axi_interconnect_0_imp_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_cc_1 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_cc_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_ds_0/system_axi_interconnect_0_imp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_ds_0 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_ds_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_pc_0/system_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_ds_1/system_axi_interconnect_0_imp_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_ds_1 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_ds_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_pc_1/system_axi_interconnect_0_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_pc_1 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_pc_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_ds_2/system_axi_interconnect_0_imp_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_ds_2 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_ds_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_pc_2/system_axi_interconnect_0_imp_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_pc_2 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_pc_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_ds_3/system_axi_interconnect_0_imp_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_ds_3 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_ds_3} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_pc_3/system_axi_interconnect_0_imp_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_pc_3 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_pc_3} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_ds_4/system_axi_interconnect_0_imp_auto_ds_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_ds_4 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_ds_4} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_pc_4/system_axi_interconnect_0_imp_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_pc_4 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_pc_4} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_cc_0/system_axi_interconnect_0_imp_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_cc_0 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_cc_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_ds_5/system_axi_interconnect_0_imp_auto_ds_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_ds_5 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_ds_5} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_ds_6/system_axi_interconnect_0_imp_auto_ds_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_ds_6 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_ds_6} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_pc_5/system_axi_interconnect_0_imp_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_pc_5 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_pc_5} -quiet] -quiet

# XDC: x:/final_project_v4.gen/sources_1/bd/system/system_ooc.xdc
