-- Generated by ChatGPT

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity tb_top_hw4 is
-- Testbench has no ports
end tb_top_hw4;

architecture behavior of tb_top_hw4 is

    -- Component Declaration for the Unit Under Test (UUT)
    component top_hw4
        Port (
            clk : in STD_LOGIC;
            reset : in STD_LOGIC;
            ctrl : in STD_LOGIC;
            Q1 : out unsigned(2 downto 0);
            Q0 : out unsigned(2 downto 0)
        );
    end component;

    -- Signals for the testbench
    signal clk   : STD_LOGIC := '0';
    signal reset : STD_LOGIC := '0';
    signal ctrl  : STD_LOGIC := '0';
    signal Q1    : unsigned(2 downto 0);
    signal Q0    : unsigned(2 downto 0);

    -- Clock period constant
    constant clk_period : time := 10 ns;

begin

    -- Instantiate the Unit Under Test (UUT)
    uut: top_hw4
        Port map (
            clk => clk,
            reset => reset,
            ctrl => ctrl,
            Q1 => Q1,
            Q0 => Q0
        );

    -- Clock process
    clk_process : process
    begin
        while true loop
            clk <= '0';
            wait for clk_period / 2;
            clk <= '1';
            wait for clk_period / 2;
        end loop;
    end process;

    -- Stimulus process
    stimulus_process : process
    begin
        -- Initial conditions
        ctrl <= '0';
        reset <= '0';
        wait for clk_period; -- Wait 1 clock cycle

        -- Set reset to '1'
        reset <= '1';
        wait for clk_period; -- Wait 1 clock cycle

        -- Set ctrl to '1' and wait 4 clock cycles
        ctrl <= '1';
        wait for 4 * clk_period;

        -- Set ctrl to '0' and wait 3 clock cycles
        ctrl <= '0';
        wait for 3 * clk_period;

        -- Set ctrl to '1' and wait 7 clock cycles
        ctrl <= '1';
        wait for 7 * clk_period;

        -- Set reset to '0'
        reset <= '0';

        -- Stop simulation
        wait;
    end process;

end behavior;

